#!/bin/sh

cat <<EOF > index.html
<!DOCTYPE html>
<html lang="hu">
    <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{Document Title}</title>
	<link rel="stylesheet" href="/style.css">
	<!-- <link rel="icon" href="/favicon.ico" type="image/x-icon"> -->
    </head>
    <body>
	<script src="/scripts/index.js"></script>
    </body>
</html>
EOF

mkdir -p css imgs scripts

cat <<EOF > ./css/style.css
html {
    box-sizing: border-box;
}

body {
    margin: 0;
    padding: 0;
}
EOF

cat <<EOF > ./scripts/index.js
console.log("Hello World!");
EOF

touch ./imgs/sample.png
